---
ignore:
  - README.md:11
  - README.md:16
  - lib/glyptodont/checkers/counter.rb:28
  - lib/glyptodont/checkers/counter.rb:30
  - lib/glyptodont/todo_researcher.rb:32
  - lib/glyptodont/todo_researcher.rb:33
  - lib/glyptodont/todo_researcher.rb:34
  - lib/glyptodont/todo_researcher.rb:35
